stages:
  - test  # Run tests first
  - build  # Run build after tests
  - deploy  # Run deploy after build

services:
  - postgres: 14.2-bullseye

variables:
  POSTGRES_PASSWORD: test
  DATABASE_URL: postgresql://postgres:test@postgres:5432/postgres

## TESTING
monolith-api-unit-test-job:
  image: python:3-bullseye
  stage: test
  script:
    - cd monolith/api
    - pip install -r requirements.txt
    # - export DATABASE_URL
    # - python manage.py migrate  # Migrate the database
    - python manage.py test  # Run the tests

accounts-api-unit-test-job:
image: python:3-bullseye
stage: test
script:
  - cd accounts_microservice
  - pip install -r requirements.txt
  # - export DATABASE_URL
  # - python manage.py migrate # Migrate the database
  - python manage.py test # Run the tests

lint-project-job:
  image: python:3-bullseye
  stage: test
  script:
    - pip install flake8
    - flake8 monolith  # Run flake8 on project ot check for code quality

