volumes:
    postgres-data:
        external: true
    mongo-data:
        external: true
services:
    postgres:
        build:
            context: ./relational-data
            dockerfile: ./Dockerfile.dev
        volumes:
            - postgres-data:/var/lib/postgresql/data
        environment:
            - POSTGRES_MULTIPLE_DATABASES=postgresdata,
            - POSTGRES_PASSWORD=inthenameofdog
        ports:
            - 15432:5432
    mongo:
        image: mongo:5
        volumes:
            - mongo-data:/data/db
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: password
    monolith:
        build:
            context: ./monolith
            dockerfile: ./Dockerfile.dev
        ports:
            - "8080:8000"
        volumes:
            - ./monolith:/app
        environment:
            DATABASE_URL: postgresql://user-name:password@postgres/db-name
            WAIT_HOSTS: postgres:5432
    ghi:
        image: node:lts-bullseye
        command: /bin/bash run.sh
        working_dir: /app
        volumes:
            - ./ghi:/app
        ports:
            - "3000:3000"
        environment:
            HOST_OS: ${OS}
            NODE_ENV: development
            HOST: "0.0.0.0"
            REACT_APP_DJANGO_SERVICE: http://localhost:8080