# Generated by Django 4.0.3 on 2022-09-02 00:54

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OwnerVO',
            fields=[
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.BigIntegerField(validators=[django.core.validators.MaxValueValidator(9999999999)])),
                ('description', models.TextField(max_length=1000)),
                ('account_number', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('state', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Dog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('age', models.SmallIntegerField(blank=True, null=True)),
                ('breed', models.CharField(default='mix', max_length=100)),
                ('description', models.TextField(blank=True, max_length=1000, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner', to='puppylove_rest.ownervo')),
            ],
        ),
        migrations.CreateModel(
            name='AWSPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('upload', models.FileField(upload_to='')),
                ('owner_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='photo', to='puppylove_rest.ownervo')),
            ],
        ),
    ]
