# Generated by Django 4.0.3 on 2022-08-29 19:36

import django.core.validators
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OwnerVO',
            fields=[
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(9999999999)])),
                ('description', models.TextField(max_length=1000)),
                ('account_number', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('state', models.CharField(max_length=2)),
            ],
        ),
    ]
