# Generated by Django 4.0.3 on 2022-08-22 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puppylove_rest', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dog',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
    ]
