# Generated by Django 4.0.3 on 2022-08-23 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puppylove_rest', '0004_dog_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owner',
            name='phone',
            field=models.PositiveSmallIntegerField(max_length=10),
        ),
        migrations.AlterField(
            model_name='state',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
