# Generated by Django 4.0.3 on 2022-08-23 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puppylove_rest', '0006_alter_owner_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owner',
            name='phone',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
