# Generated by Django 4.0.3 on 2022-08-23 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puppylove_rest', '0007_alter_owner_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='dog',
            name='documentation',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
