# Generated by Django 4.0.3 on 2022-08-23 22:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puppylove_rest', '0008_dog_documentation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owner',
            name='phone',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(9999999999)]),
        ),
    ]
